#File Reading
inFolder: "191118_test/input"
outFolder: "191118_test/output"
interFolder: "191118_test/intermediaries"
gzvcf_suffix: ".vcf.gz"

#QC Metrics
MISS_THRESH_SNP: 0.15
MISS_THRESH_INDI: .1
RELATEDNESS_THRESH: .125
MAF: .01
HWE: .00000001
