#File Reading

dataCode: "NYGC_Freeze02_European_Feb2020"

#Options
#keepAllFiles: False #If True, keeps the results of the individual filters. If false, only keeps the final output files, and statistics
splitFinalVCF: False #If true, splits the final vcf on chromosome and writes them to separate files in the output folder
filterBlacklist: True #if true, filters based on a provided blacklist file. Blast list must be put in input folder and be in bed format
blacklistFile: "data/hg38-blacklist.v2.bed.gz" # from https://github.com/Boyle-Lab/Blacklist/blob/master/lists/hg38-blacklist.v2.bed.gz; ref: https://www.nature.com/articles/s41598-019-45839-z
MAF_threshold: 0.01
liftOverhg19hg38: False
removeSamples: "data/2020_02_28_non_european_and_sex_fails_vcf_ids.txt"

vcfFileList: "NYGC_Freeze02_European_Feb2020/NYGC_Freeze_02_recalibrated_variants.vcf_list.txt"
#Chunking Metric
NUM_CHUNK: 4
#how much to break up each chromosome. Higher values will run faster but reserve more nodes
chromosomeLengths: "data/hg38_chrSizes.txt"

#QC Metrics
GDP: 10 #Genotype level read depth
GQ: 20 #Genome Quality
MISS_THRESH_SNP: 0.15 #Missingness threshold for a SNP to be excluded. Default is .15
ODP: 5000 #Overall Read Depth #paper uses 25000, but that's too large for the ALS data
MQ_MIN: 58.75 #Mapping Quality lower threshold
MQ_MAX: 61.25 #Mapping Quality upper threshold
VQSLOD: 7.81 #lower threshold for VQSLOD
INBREEDING_COEF: -0.8 #analogous to HWE. Default: -0.8
MISS_THRESH_INDI: .1 #Missingness threshold for an individual to be excluded. Default is .1
RELATEDNESS_THRESH: .125 #Relatedness threshold based on the King et al method (Relatedness2 option)
