#File Reading
inFolder: "191120_test/input"
outFolder: "191120_test/output"
tempFolder: "191120_test/temp"
statsFolder: "191120_test/stats"
gzvcf_suffix: ".vcf.gz"

#QC Metrics
GDP: 10 #Genotype level read depth
GQ: 20 #Genome Quality
MISS_THRESH_SNP: 0.15 #Missingness threshold for a SNP to be excluded. Default is .15
ODP: 5000 #Overall Read Depth #paper uses 25000, but that's too large for the ALS data
MQ_MIN: 58.75 #Mapping Quality lower threshold
MQ_MAX: 61.25 #Mapping Quality upper threshold
VQSLOD: 7.81 #lower threshold for VQSLOD
INBREEDING_COEF: -0.8 #analogous to HWE. Default: -0.8
MISS_THRESH_INDI: .1 #Missingness threshold for an individual to be excluded. Default is .1
RELATEDNESS_THRESH: .125 #Relatedness threshold based on the King et al method (Relatedness2 option in vcftools). Default is .125 (first cousins)
